export const GET_SMURFS = 'GET_SMURFS';
export const POST_SMURF = 'POST_SMURF';
export const GET_SMURFS_SUCCESS = 'ADD_SMURFS_SUCCESS';
export const GET_SMURFS_FAILURE = 'ADD_SMURFS_FAILURE';
export const ON_INPUT_CHANGE = 'ON_INPUT_CHANGE';
export const RESET = 'RESET';